name: auto test

on: [push]

jobs:
  build:

    runs-on: [self-hosted, linger]

    steps:
      - uses: actions/checkout@v3
      - name: activate python env
        run: |
          source /S512G/install/conda/bin/activate
          conda activate linger_autotest_37
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          sh auto_test.sh