name: auto test

on: [push]

jobs:
  build:

    runs-on: [self-hosted, Linux , X64 , linger]

    steps:
      - uses: actions/checkout@v3
      - name: activate python env
        run: |
          conda create --name linger_env python=3.7
          source activate linger_env
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          sh auto_test.sh